crawlerForDouban/toDoApp/urls.py
from django.contrib import admin
from django.urls import path,include
import todolist.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todolist.urls')),
]

crawlerForDouban/todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'
urlpatterns = [
    path('home/', views.home,name="主页"),
    path('about/', views.about,name="关于"),
    path('suibi/', views.suibi,name="随笔"),
    path('shige/', views.shige,name="诗歌"),
    path('xiaoshuo/', views.xiaoshuo,name="小说"),
]

crawlerForDouban/todolist/models.py
from django.db import models

# Create your models here.

crawlerForDouban/todolist/views.py
from django.shortcuts import render,redirect
import requests
from bs4 import BeautifulSoup

# Create your views here.
lst=[

]

content = {

}

def home(request):
    global lst
    global content
    return render(request,'todolist/home.html',content)

def about(request):
    return render(request,'todolist/about.html')

def suibi(request):
    global lst
    global content
    lst.clear()
    content.clear()

    #爬虫程序
    res = requests.get("https://www.douban.com/tag/%E9%9A%8F%E7%AC%94/?source=related")
    soup = BeautifulSoup(res.text,"lxml")
    book_div = soup.find(attrs={"id":"book"})
    #标题
    book_a = book_div.findAll(attrs={"class":"title"})
    #图片链接
    book_img = book_div.findAll('img')

    for i in range(9):
        lst.append({'title':book_a[i].string,'img':book_img[i].get('src')})
    
    content= {'清单':lst,'信息':'爬取随笔成功'}
    return redirect('todolist:主页')

def shige(request):
    global lst
    global content
    lst.clear()
    content.clear()

    #爬虫程序
    res = requests.get("https://www.douban.com/tag/%E8%AF%97%E6%AD%8C/?source=related")
    soup = BeautifulSoup(res.text,"lxml")
    book_div = soup.find(attrs={"id":"book"})
    #标题
    book_a = book_div.findAll(attrs={"class":"title"})
    #图片链接
    book_img = book_div.findAll('img')
    
    for i in range(9):
        lst.append({'title':book_a[i].string,'img':book_img[i].get('src')})
    
    content= {'清单':lst,'信息':'爬取诗歌成功'}
    return redirect('todolist:主页')

def xiaoshuo(request):
    global lst
    global content
    lst.clear()
    content.clear()

    #爬虫程序
    res = requests.get("https://www.douban.com/tag/%E5%B0%8F%E8%AF%B4/?source=related")
    soup = BeautifulSoup(res.text,"lxml")
    book_div = soup.find(attrs={"id":"book"})
    #标题
    book_a = book_div.findAll(attrs={"class":"title"})
    #图片链接
    book_img = book_div.findAll('img')
   
    for i in range(9):
        lst.append({'title':book_a[i].string,'img':book_img[i].get('src')})
    
    content= {'清单':lst,'信息':'爬取小说成功'}
    return redirect('todolist:主页')

crawlerForDouban/todolist/templates/todolist/about.html
{% extends 'todolist/base.html' %}

{% block 标题 %}关于本站
{% endblock 标题 %}


{% block 待办 %} "{% url 'todolist:主页'%}"
{% endblock 待办 %} 

{% block css %}todolist/about.css
{% endblock css %}

{% block 主体 %}
<br>
<h4>
    一款小巧的爬取豆瓣网的数据显示网站
</h4>

{% endblock 主体 %}
  

crawlerForDouban/todolist/templates/todolist/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block 标题 %}未命名{% endblock 标题 %}</title>

    <link rel="shortcut icon" href="{% static 'todolist/icons/icon_list.png' %}">

    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'todolist/css/base.css' %}">
    <link rel="stylesheet" href={% block css %} {% endblock css %}>
  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="navtop">
      <a class="navbar-brand" href={% block 待办 %}#{% endblock 待办 %}>
            <img src="{% static 'todolist/images/logo_list.png'%}" width="33" height="33" class="d-inline-block align-top">爬取豆瓣网</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href= {% block 关于 %}#{% endblock 关于 %}>关于本站</a>
          </li>
        </ul>

        <form method="POST" action="{% url 'todolist:随笔' %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-sm">随笔</button>
        </form>

        <form method="POST" action="{% url 'todolist:诗歌' %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-sm">诗歌</button>
        </form>

        <form method="POST" action="{% url 'todolist:小说' %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-sm">小说</button>
        </form>

      </div>
    </nav>

    <main role='main' class='container'>
    
    {% block 主体 %}
        
    {% endblock 主体 %}
        
    </main>     
        <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      </body>
    </html>

crawlerForDouban/todolist/templates/todolist/home.html
{% extends 'todolist/base.html' %}
{% load static %}

{% block 标题 %}您的豆瓣数据显示页
{% endblock 标题 %}


{% block css %}"{% static 'todolist/css/home.css' %}"
{% endblock css %}


{% block 关于 %}"{% url 'todolist:关于'%}"{% endblock 关于 %}  

{% block 主体 %}
  
{% if 信息 %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  <strong>{{信息}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>  
{% endif %}
<br>
<div class = 'table-responsive'>
        <table class="table table-hover">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">序号</th>
                    <th scope="col">封面</th>
                    <th scope="col">书名</th>
                  </tr>
                </thead>
                 <tbody>

                  {% for item in 清单 %}
                      <tr class="table-dark">
                        <th calss ="text-dark" scope="row">{{forloop.counter}}</th>
                        <td><img src="{{item.img}}" height="148" width="100"></td>
                        <td class = "text-dark">{{item.title}}</td>
                      </tr>
                    
                  {% endfor %}
                     
                </tbody> 
              </table>



</div>

{% endblock 主体 %}